Feat refactor code
Sheetal-Ravindran/realtime-react-app pull request #3
Opened 2021-05-23 14:25 UTC by Sheetal-Ravindran

2021-05-25 11:17 UTC, rr235 requested changes

2021-05-25 11:17 UTC, rr235 commented on README.md
> +# realtime-react-app
Add steps to run the setup.

example

## Run Applictiion

1. npm install
2. npm start

This will run app in localhost:whatever port by default

2021-05-25 11:17 UTC, rr235 commented on src/components/BasicDetails.js
> +class BasicDetails extends React.Component {
Nice effort. :)

Even though you are using this for showing some basic details, you cant name it as `BasicDetails`, its raises some confusion.

Sugggestions
- `Input` 
- `TextField`
- `FormInput`

Have a look at **Material UI**. This is a react component library created by google https://material-ui.com/components/text-fields/ - They call it `FormField`

Another example is **Vue Storefront UI**, they call it `Input` https://docs.storefrontui.io/?path=/docs/components-atoms-input--common (this is in vuejs btw)

2021-05-25 11:17 UTC, rr235 commented on src/components/BasicDetails.js
>          <label className="label" htmlFor="name">
Pls add condition to show or hide label if `label` is not passed

2021-05-25 11:17 UTC, rr235 commented on src/index.js
>  import './mysass.scss';
Come up with a meedingful file name

2021-05-28 19:09 UTC, rr235 requested changes
just reviewed only a bit. something for you work on

2021-05-28 19:09 UTC, rr235 commented on README.md
> +# Run Application
Wheres the title of the project?

2021-05-28 19:09 UTC, rr235 commented on package.json
> +    "@material-ui/core": "^4.11.4",
woah! not sure what happened here, why do you need this package?

2021-05-28 19:09 UTC, rr235 commented on src/components/FormInput.js
> +    console.log("onInputChange");
remove `console.log`

2021-05-28 19:09 UTC, rr235 commented on src/components/FormInput.js
> +  validateField(fieldName, value) {
its a bit dangerous to build a logic just around name. i would recommend you to create a prop called `type` which would have two types of values `text` or `number`, if its type `text` something like

```
switch (this.props.type) {
   case 'text':
...

```

2021-06-04 13:19 UTC, rr235 requested changes

2021-06-04 13:19 UTC, rr235 commented on src/main.scss
> +  font: 14px/24px "Lato", Arial, sans-serif;
do you know what this `14px/24px` expression means?

2021-06-04 13:19 UTC, rr235 commented on src/main.scss
> +}
where is this class used?
remove unused styles

2021-06-04 13:19 UTC, rr235 commented on src/components/FormInput.js
> +
Create a new `.scss` called `formInput.scss` and import it here.

Move the classes required by this component from `main.scss` to `formInput.scss`

Also move the required variables with it

2021-06-04 13:19 UTC, rr235 commented on src/main.scss
> +}
quite an odd name for the `heading` class

2021-06-04 13:19 UTC, rr235 commented on src/index.js
> +          <FormInput label = "Enter First Name " type = "text"/>
```suggestion
          <FormInput label="Enter First Name " type="text"/>
```
We generally dont leave space before and after `=` in html code

2021-06-04 13:19 UTC, rr235 commented on src/components/FormInput.js
> +    let errorMessage = this.state.errorMessage;
```suggestion
    let errorMessage = '';
```
this is fine, you are not using the `this.state.errorMessage` down the line. By doing this you dont have to reset the `errorMessage` in lines 26-28 (remove the else condition)

2021-06-04 13:19 UTC, rr235 commented on src/main.scss
> +.input-field:focus ~ .label-text
btw do you know `~` is used here for?

2021-06-04 13:19 UTC, rr235 commented on src/main.scss
> +.input-field:focus ~ .label-text
the bug of label sliding back to the original place is do the fact that styling is built on `:focus` state

Depending on `focus` state is fine, but you need to build a bit more logic around it

2021-06-04 13:19 UTC, rr235 commented on src/components/FormInput.js
> +          <label className="label-text">{this.props.label}</label>
C'mon why would you put `label` after `input`? it should be `label` then `input`, change the stying logic accordingly.

2021-06-04 13:20 UTC, rr235 commented
Can you do these changes in about an hour, dont worry about fixing the label logic, i ll pair with you in an hour and build it together

2021-06-04 16:36 UTC, Sheetal-Ravindran commented on src/main.scss
> +  font: 14px/24px "Lato", Arial, sans-serif;
14px/24px means
font size - 14px
line height - 24px

2021-06-13 11:38 UTC, rr235 approved these changes
I think this is good as an initial version. Nice one!

2021-06-13 11:38 UTC, rr235 commented on src/components/FormInput.js
> +          <br></br>
never use `<br />` unless its really. if you want some space below use css to do that.

Create a new PR to fix it

2021-06-14 18:06 UTC, merged